# Generated by Django 4.1.7 on 2023-03-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stagiaire.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiaire', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=stagiaire.models.renomer_image)),
                ('sex', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], default='homme', max_length=50)),
                ('start_stage', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_stage', models.DateField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.filiaire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stagiaire.filiaire')),
            ],
        ),
    ]
