# Generated by Django 4.1.7 on 2023-03-07 17:58

from django.db import migrations, models
import stagiaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=1, upload_to=stagiaire.models.renomer_image),
            preserve_default=False,
        ),
    ]
