# Generated by Django 4.1.7 on 2023-03-07 18:08

from django.db import migrations, models
import stagiaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0005_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to=stagiaire.models.renomer_image),
        ),
    ]
