# Generated by Django 4.1.7 on 2023-03-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0006_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiaire',
            name='bureau',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
